" Vim with all enhancements
source $VIMRUNTIME/vimrc_example.vim

" Use the internal diff if available.
" Otherwise use the special 'diffexpr' for Windows.
if &diffopt !~# 'internal'
  set diffexpr=MyDiff()
endif
function MyDiff()
  let opt = '-a --binary '
  if &diffopt =~ 'icase' | let opt = opt . '-i ' | endif
  if &diffopt =~ 'iwhite' | let opt = opt . '-b ' | endif
  let arg1 = v:fname_in
  if arg1 =~ ' ' | let arg1 = '"' . arg1 . '"' | endif
  let arg1 = substitute(arg1, '!', '\!', 'g')
  let arg2 = v:fname_new
  if arg2 =~ ' ' | let arg2 = '"' . arg2 . '"' | endif
  let arg2 = substitute(arg2, '!', '\!', 'g')
  let arg3 = v:fname_out
  if arg3 =~ ' ' | let arg3 = '"' . arg3 . '"' | endif
  let arg3 = substitute(arg3, '!', '\!', 'g')
  if $VIMRUNTIME =~ ' '
    if &sh =~ '\<cmd'
      if empty(&shellxquote)
        let l:shxq_sav = ''
        set shellxquote&
      endif
      let cmd = '"' . $VIMRUNTIME . '\diff"'
    else
      let cmd = substitute($VIMRUNTIME, ' ', '" ', '') . '\diff"'
    endif
  else
    let cmd = $VIMRUNTIME . '\diff'
  endif
  let cmd = substitute(cmd, '!', '\!', 'g')
  silent execute '!' . cmd . ' ' . opt . arg1 . ' ' . arg2 . ' > ' . arg3
  if exists('l:shxq_sav')
    let &shellxquote=l:shxq_sav
  endif
endfunction

set encoding=utf8
colorscheme seoul256
au BufRead,BufNewFile *.gtd set filetype=gtd
"acao
au BufEnter *.gtd hi Character guifg=#000000 guibg=#FFFFFF
"link
au BufEnter *.gtd hi Boolean ctermfg=220
"comentario
au BufEnter *.gtd hi Number guifg=#FFF896
"informacao
au BufEnter *.gtd hi Float guifg=#D4FFC4
"decisao
au BufEnter *.gtd hi Identifier ctermfg=0 ctermbg=216
"duvida
au BufEnter *.gtd hi Statement guifg=#C6C4FF gui=none
"aguardo
au BufEnter *.gtd hi Label guifg=#a9cbcf
"fazer
au BufEnter *.gtd hi Type guibg=#FFFFFF guifg=#888888 gui=none
"!
au BufEnter *.gtd hi Comment guifg=#666666
"#
au BufEnter *.gtd hi Operator guifg=#FFFFFF guibg=#DDAA00
"PreProc
au BufEnter *.gtd hi PreProc guifg=#FFD0A1
noremap gf :e <cfile><cr>
