set autoindent
set smartindent
set cindent
set tabstop=4
set shiftwidth=4
set background=light
set hlsearch
set number
set title
set laststatus=2
set relativenumber
set ignorecase
nnoremap <C-Up> <Up>ddp<Up>
nnoremap <C-Down> ddp
highlight LineNr ctermfg=grey
au BufNewFile *.c r ~/.vim/template.c
colorscheme seoul256
let g:vim_markdown_toc_autofit = 1

call plug#begin('~/.vim/plugged')
Plug 'scrooloose/nerdtree'
Plug 'itchyny/lightline.vim'
Plug 'mileszs/ack.vim'
Plug 'godlygeek/tabular'
Plug 'preservim/vim-markdown'
call plug#end()

autocmd VimEnter * NERDTree | wincmd p
set clipboard=unnamedplus
au VimEnter * if &diff | execute 'windo set wrap' | endif
"noremap gf :e <cfile><cr>

au BufRead,BufNewFile *.gtd set filetype=gtd
"acao
au BufEnter *.gtd hi Character ctermfg=black ctermbg=white
"link
au BufEnter *.gtd hi Boolean ctermfg=220
"comentario
au BufEnter *.gtd hi Number ctermfg=lightyellow
"informacao
au BufEnter *.gtd hi Float ctermfg=lightgreen
"decisao
au BufEnter *.gtd hi Identifier ctermfg=lightred
"duvida
au BufEnter *.gtd hi Statement ctermfg=lightblue gui=none
"aguardo
au BufEnter *.gtd hi Label ctermfg=lightcyan
"fazer
au BufEnter *.gtd hi Type ctermfg=white ctermbg=grey gui=none
"!
au BufEnter *.gtd hi Comment ctermfg=grey
"#
au BufEnter *.gtd hi Operator ctermfg=white ctermbg=blue
"PreProc
au BufEnter *.gtd hi PreProc ctermfg=blue
noremap gf :e <cfile><cr>

au BufRead,BufNewFile *.ref set filetype=ref
au BufEnter *.ref hi Constant ctermfg=15 ctermbg=28
au BufEnter *.ref hi String ctermfg=0 ctermbg=251
au BufEnter *.ref hi Character ctermfg=15 ctermbg=203

au BufEnter *.c hi Comment ctermbg=230
